### ISSUE TITLE
Binary Tree ZigZag Level Order Traversal

### ISSUE THREAD

**Issue by harshita9621** [avijitsen7076/Interview-Prep#59]
@ashavijit Can I work on this issue

**Comment by avijitsen7076** [comment]
@harshita9621 go!

**Comment by harshita9621** [comment]
@avijitsen7076 Is this repo part of Hacktoberfest

**Comment by avijitsen7076** [comment]
> @avijitsen7076 Is this repo part of Hacktoberfest

yup!

**Comment by SakshamSharma07** [comment]
@avijitsen7076  i want to work on this problem , please assign me this problem

**Comment by arin2002** [comment]
@avijitsen7076 assign me too
